import Link from "next/link";
import { metadata as pipelineMeta } from "@/lib/data";
import { EVIDENCE_COLORS } from "@/lib/utils";
import type { EvidenceTier } from "@/lib/types";

const EVIDENCE_TIERS: { tier: EvidenceTier; description: string }[] = [
  {
    tier: "validated",
    description:
      "Experimentally confirmed reaction with published kinetic or structural data (EC number, PMID, or BRENDA entry).",
  },
  {
    tier: "predicted",
    description:
      "Computationally predicted from homologous enzyme sequences or known reaction families with high confidence.",
  },
  {
    tier: "inferred",
    description:
      "Inferred from pathway context, thermodynamic feasibility, or partial experimental evidence.",
  },
  {
    tier: "hypothetical",
    description:
      "Chemically plausible reaction enumerated from stereochemical rules with no direct experimental support.",
  },
];

export default function AboutPage() {
  const { pipeline_version, generated_at, counts } = pipelineMeta;

  const generatedDate = new Date(generated_at).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="flex flex-1 flex-col px-4 py-10 sm:px-6">
      <div className="mx-auto w-full max-w-3xl space-y-12">

        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-zinc-100">
            About SUGAR
          </h1>
          <p className="mt-4 text-zinc-300 leading-relaxed">
            SUGAR (Sugar Utilization and General Anabolic Routes) is a
            computational database and pathway explorer for carbohydrate
            metabolites and their enzymatic interconversions. It enumerates
            monosaccharides, polyols, phosphorylated sugars, and related
            compounds from first principles of stereochemistry, then generates a
            reaction network connecting them via known and predicted enzymatic
            transformations.
          </p>
          <p className="mt-4 text-zinc-300 leading-relaxed">
            The goal of SUGAR is to make the full landscape of sugar biochemistry
            navigable: from finding synthetic routes between rare monosaccharides,
            to understanding which reactions are well-supported by experimental
            evidence versus which are computationally inferred. Every compound,
            reaction, and pathway is tagged with provenance metadata so
            researchers can calibrate their trust in each result.
          </p>
          <p className="mt-4 text-zinc-300 leading-relaxed">
            The web interface provides a compound browser, reaction browser,
            k-shortest-path finder, and an interactive network graph — all
            filterable by evidence tier so you can focus on only the reactions
            you trust.
          </p>
        </div>

        {/* Methodology */}
        <div>
          <h2 className="text-xl font-semibold text-zinc-100">Methodology</h2>

          <div className="mt-6 space-y-6">
            <div>
              <h3 className="text-sm font-semibold uppercase tracking-wider text-zinc-400">
                Compound enumeration
              </h3>
              <p className="mt-2 text-sm text-zinc-400 leading-relaxed">
                Monosaccharides are enumerated by systematically assigning
                R/S stereocenters to a carbon backbone of length 2&ndash;7 while
                enforcing chemical valence rules. The enumeration covers all
                aldoses, ketoses, deoxy sugars, amino sugars, and their
                corresponding polyols and lactones. Each compound is assigned a
                canonical identifier, molecular formula, and stereocenters list.
                A separate pass resolves common names and aliases from a curated
                synonym table (covering IUPAC names, trivial names, and CAS
                synonyms).
              </p>
            </div>

            <div>
              <h3 className="text-sm font-semibold uppercase tracking-wider text-zinc-400">
                Reaction generation
              </h3>
              <p className="mt-2 text-sm text-zinc-400 leading-relaxed">
                Reactions are generated by applying reaction templates to
                compatible substrate pairs. Templates encode the bond-breaking
                and bond-forming logic for each reaction class (epimerization,
                isomerization, reduction/oxidation, phosphorylation,
                nucleotidyl-transfer, etc.). Each template produces a candidate
                reaction which is then checked for thermodynamic plausibility
                using estimated &Delta;G values. Reactions matching entries in
                RHEA, BRENDA, or UniProt are promoted from hypothetical to
                validated or predicted tiers based on the quality of the match.
              </p>
            </div>

            <div>
              <h3 className="text-sm font-semibold uppercase tracking-wider text-zinc-400">
                Pathway finding
              </h3>
              <p className="mt-2 text-sm text-zinc-400 leading-relaxed">
                The reaction network is stored as a directed graph where nodes
                are compounds and edges are reactions weighted by a cost score
                (lower is better). Pathway finding uses Yen&#39;s k-shortest
                paths algorithm to enumerate diverse routes between a source and
                target compound. Results can be filtered by evidence tier so
                that, for example, only pathways composed entirely of validated
                reactions are shown.
              </p>
            </div>
          </div>
        </div>

        {/* Evidence tier legend */}
        <div>
          <h2 className="text-xl font-semibold text-zinc-100">
            Evidence Tiers
          </h2>
          <p className="mt-2 text-sm text-zinc-400">
            Each reaction is assigned an evidence tier reflecting the strength
            of experimental or computational support.
          </p>
          <div className="mt-4 space-y-3">
            {EVIDENCE_TIERS.map(({ tier, description }) => (
              <div
                key={tier}
                className="flex gap-3 rounded-lg border border-zinc-800 bg-zinc-900/60 p-4"
              >
                <div className="shrink-0 pt-0.5">
                  <span
                    className={`inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium capitalize ${EVIDENCE_COLORS[tier]}`}
                  >
                    {tier}
                  </span>
                </div>
                <p className="text-sm text-zinc-400 leading-relaxed">
                  {description}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Data version */}
        <div>
          <h2 className="text-xl font-semibold text-zinc-100">Data Version</h2>
          <div className="mt-4 rounded-lg border border-zinc-800 bg-zinc-900/60 p-4">
            <dl className="grid grid-cols-2 gap-x-8 gap-y-3 text-sm sm:grid-cols-3">
              <div>
                <dt className="text-zinc-500">Pipeline version</dt>
                <dd className="font-mono text-zinc-200">{pipeline_version}</dd>
              </div>
              <div>
                <dt className="text-zinc-500">Generated</dt>
                <dd className="text-zinc-200">{generatedDate}</dd>
              </div>
              <div>
                <dt className="text-zinc-500">Total compounds</dt>
                <dd className="text-zinc-200">{counts.total_compounds.toLocaleString()}</dd>
              </div>
              <div>
                <dt className="text-zinc-500">Total reactions</dt>
                <dd className="text-zinc-200">{counts.total_reactions.toLocaleString()}</dd>
              </div>
              {counts.monosaccharides !== undefined && (
                <div>
                  <dt className="text-zinc-500">Monosaccharides</dt>
                  <dd className="text-zinc-200">{counts.monosaccharides.toLocaleString()}</dd>
                </div>
              )}
              {counts.polyols !== undefined && (
                <div>
                  <dt className="text-zinc-500">Polyols</dt>
                  <dd className="text-zinc-200">{counts.polyols.toLocaleString()}</dd>
                </div>
              )}
              {counts.epimerizations !== undefined && (
                <div>
                  <dt className="text-zinc-500">Epimerizations</dt>
                  <dd className="text-zinc-200">{counts.epimerizations.toLocaleString()}</dd>
                </div>
              )}
              {counts.isomerizations !== undefined && (
                <div>
                  <dt className="text-zinc-500">Isomerizations</dt>
                  <dd className="text-zinc-200">{counts.isomerizations.toLocaleString()}</dd>
                </div>
              )}
              {counts.reductions !== undefined && (
                <div>
                  <dt className="text-zinc-500">Reductions</dt>
                  <dd className="text-zinc-200">{counts.reductions.toLocaleString()}</dd>
                </div>
              )}
            </dl>
          </div>
        </div>

        {/* Links */}
        <div>
          <h2 className="text-xl font-semibold text-zinc-100">Links</h2>
          <div className="mt-4 flex flex-wrap gap-3">
            <Link
              href="https://github.com/rivirside/sugar-v2"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-lg border border-zinc-700 bg-zinc-900 px-4 py-2 text-sm text-zinc-300 transition-colors hover:border-zinc-500 hover:text-zinc-100"
            >
              <svg
                className="h-4 w-4"
                viewBox="0 0 24 24"
                fill="currentColor"
                aria-hidden="true"
              >
                <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0 1 12 6.844a9.59 9.59 0 0 1 2.504.337c1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.02 10.02 0 0 0 22 12.017C22 6.484 17.522 2 12 2z" />
              </svg>
              GitHub: rivirside/sugar-v2
            </Link>
          </div>
        </div>

      </div>
    </div>
  );
}
